name: Test get_brand function

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test-get-brand:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'devel'
          http-user-agent: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install package
        run: R CMD INSTALL .

      - name: Run get_brand tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHA_TEST: true
        run: Rscript tests/manual/github-get-brand.R