name: Test get_brand function

on:
  push:
    branches: [ main, 28-get-from-repo ]
  pull_request:
    branches: [ main ]

jobs:
  test-get-brand:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev

      - name: Install R package dependencies
        run: |
          install.packages(c('yaml', 'devtools'))
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Run get_brand tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: Rscript tests/manual/github-get-brand.R